const { app } = require("./app");
require("dotenv").config();
const port = 5000;
const productRoutes = require("./routes/products");
const supplierRoutes = require("./routes/suppliers");
const messageRoutes = require("./routes/messages");
const ordersRouter = require("./routes/orders");
const usersRouter = require("./routes/users");
const discount = require("./routes/discounts");
const tax = require("./routes/tax");
const orderList = require("./routes/ListOfOrders");
const diagram = require("./routes/dashboard");
const revenueRoutes = require("./routes/revenueRoutes");
const productsRoutes = require("./routes/productOrders");
const suppliersOrdersRouter = require("./routes/suppliersOrders");
const ordersFromSuppliers = require("./routes/ordersFromSuppliers");
const sendEmailToSuppliers = require("./routes/sendEmailToSupplier");
const forgot = require("./routes/ForgotPassword");
const profile = require("./routes/userProfile");
app.use("/api/userProfile", profile);
app.use("/api/ForgotPassword", forgot);
app.use("/api/sendEmailToSuppliers", sendEmailToSuppliers);
app.use("/api/ordersFromSuppliers", ordersFromSuppliers);
app.use("/api/suppliersOrders", suppliersOrdersRouter);
app.use("/api/productOrders", productsRoutes);
app.use("/api/revenue", revenueRoutes);
app.use("/api/ListOfOrders", orderList);
app.use("/api/discounts", discount);
app.use("/api/tax", tax);
app.use("/api/orders", ordersRouter);
app.use("/api/users", usersRouter);
app.use("/api/products", productRoutes);
app.use("/api/suppliers", supplierRoutes);
app.use("/api/messages", messageRoutes);
app.use("/api/dashboard", diagram);
app.listen(port, () => {
  console.log("Server started on port 5000 ");
});
